version: '3.1'
services:
  weatherman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherman
    env_file:
      - .env
    restart: always
    ports: 
      - "3002:3002"    
    logging:
      driver: "json-file"
      options:
        max-size: 100m