version: '3.1'
services:
  weatherman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherman
    environment: 
      - TZ=Europe/Madrid #do NOT change
      - LOG_LEVEL=info
      - HTTP_LOG_LEVEL=info
      - HTTP_PORT=3002
      - RAPID_API_SECRET=
      - WEATHER_LOCATION_LAT=
      - WEATHER_LOCATION_LONG=
    restart: always
    ports: 
      - "3002:3002"    
    logging:
      driver: "json-file"
      options:
        max-size: 100m