name: weatherman
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  alfred: ^1.1.0+2
  args: ^2.3.0
  cron: ^0.5.1
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0
  logger: ^1.3.0
  timezone: ^0.9.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
